%   List of Descriptors - Date: 03-Feb-2004 23:15:23
% ------------------------------------------------------
%  1 : M_g_mol-1
%  2 : Classe
%  3 : Tmin_oC
%  4 : Tmax_oC
%  5 : reference
%  6 : method
%  7 : extrapolated
%  8 : D[23oC]cm2_s-1
%  9 : logD
%  10 : Molecular area (vdW area) (Spatial Descriptors)
%  11 : Molecular volume (vdW volume) (Spatial Descriptors)
%  12 : Molecular density (Spatial Descriptors)
%  13 : Moment of inertia (magnitude) (Spatial Descriptors)
%  14 : Moment of inertia X (Spatial Descriptors)
%  15 : Moment of inertia Y (Spatial Descriptors)
%  16 : Moment of inertia Z (Spatial Descriptors)
%  17 : Radius of gyration (Spatial Descriptors)
%  18 : Ellipsoidal volume (Spatial Descriptors)
%  19 : Molecular shadow area: XY plane (Spatial Descriptors)
%  20 : Molecular shadow area: YZ plane (Spatial Descriptors)
%  21 : Molecular shadow area: ZX plane (Spatial Descriptors)
%  22 : Molecular shadow area fraction: XY plane (Spatial Descriptors)
%  23 : Molecular shadow area fraction: YZ plane (Spatial Descriptors)
%  24 : Molecular shadow area fraction: ZX plane (Spatial Descriptors)
%  25 : Molecular shadow ratio (Spatial Descriptors)
%  26 : Molecular shadow length: LX (Spatial Descriptors)
%  27 : Molecular shadow length: LY (Spatial Descriptors)
%  28 : Molecular shadow length: LZ (Spatial Descriptors)
%  29 : Dipole moment (magnitude) (Spatial Descriptors)
%  30 : Dipole moment X (Spatial Descriptors)
%  31 : Dipole moment Y (Spatial Descriptors)
%  32 : Dipole moment Z (Spatial Descriptors)
%  33 : Total charge (Atomistic Descriptors)
%  34 : Total molecular mass (Atomistic Descriptors)
%  35 : logM
%  36 : Atom count (Atomistic Descriptors)
%  37 : Element count (Atomistic Descriptors)
%  38 : Total energy (Forcite Energetics)
%  39 : Non bond energy (Forcite Energetics)
%  40 : van der Waals energy (Forcite Energetics)
%  41 : Electrostatic energy (Forcite Energetics)
%  42 : Valence energy (diag. terms) (Forcite Energetics)
%  43 : Bond energy (Forcite Energetics)
%  44 : Angle energy (Forcite Energetics)
%  45 : Torsion energy (Forcite Energetics)
%  46 : Inversion energy (Forcite Energetics)
%  47 : Rotatable bonds (Fast Descriptors)
%  48 : Hydrogen bond donor (Fast Descriptors)
%  49 : Hydrogen bond acceptor (Fast Descriptors)
%  50 : Chiral centers (Fast Descriptors)
%  51 : AlogP (Fast Descriptors)
%  52 : AlogP98 (Fast Descriptors)
%  53 : Molecular refractivity (Fast Descriptors)
%  54 : Molecular flexibility (Fast Descriptors)
%  55 : Balaban index JX (Fast Descriptors)
%  56 : Balaban index JY (Fast Descriptors)
%  57 : Wiener index (Fast Descriptors)
%  58 : Zagreb index (Fast Descriptors)
%  59 : Kappa-1 (Fast Descriptors)
%  60 : Kappa-2 (Fast Descriptors)
%  61 : Kappa-3 (Fast Descriptors)
%  62 : Kappa-1 (atom modified) (Fast Descriptors)
%  63 : Kappa-2 (atom modified) (Fast Descriptors)
%  64 : Kappa-3 (atom modified) (Fast Descriptors)
%  65 : Subgraph counts (0): path (Fast Descriptors)
%  66 : Subgraph counts (1): path (Fast Descriptors)
%  67 : Subgraph counts (2): path (Fast Descriptors)
%  68 : Subgraph counts (3): path (Fast Descriptors)
%  69 : Subgraph counts (3): cluster (Fast Descriptors)
%  70 : Subgraph counts (3): chain (Fast Descriptors)
%  71 : Chi (0) (Fast Descriptors)
%  72 : Chi (1) (Fast Descriptors)
%  73 : Chi (2) (Fast Descriptors)
%  74 : Chi (3): path (Fast Descriptors)
%  75 : Chi (3): cluster (Fast Descriptors)
%  76 : Chi (0) (valence modified) (Fast Descriptors)
%  77 : Chi (1) (valence modified) (Fast Descriptors)
%  78 : Chi (2) (valence modified) (Fast Descriptors)
%  79 : Chi (3): path (valence modified) (Fast Descriptors)
%  80 : Chi (3): cluster (valence modified) (Fast Descriptors)
%  81 : Chi (3): chain (valence modified) (Fast Descriptors)
%  82 : Information content (IC) (Fast Descriptors)
%  83 : Bond information content (BIC) (Fast Descriptors)
%  84 : Complementary information content (CIC) (Fast Descriptors)
%  85 : Structural information content (SIC) (Fast Descriptors)
%  86 : Edge adjacency/magnitude (Fast Descriptors)
%  87 : Edge distance/magnitude (Fast Descriptors)
%  88 : Vertex adjacency/equality (Fast Descriptors)
%  89 : Vertex adjacency/magnitude (Fast Descriptors)
%  90 : Vertex distance/equality (Fast Descriptors)
%  91 : Vertex distance/magnitude (Fast Descriptors)
%  92 : Atomic composition (total) (Fast Descriptors)
%  93 : E-state keys (sums): S_sCH3 (Fast Descriptors)
%  94 : E-state keys (sums): S_ssCH2 (Fast Descriptors)
%  95 : E-state keys (sums): S_dsCH (Fast Descriptors)
%  96 : E-state keys (sums): S_aaCH (Fast Descriptors)
%  97 : E-state keys (sums): S_sssCH (Fast Descriptors)
%  98 : E-state keys (sums): S_dssC (Fast Descriptors)
%  99 : E-state keys (sums): S_aasC (Fast Descriptors)
%  100 : E-state keys (sums): S_ssssC (Fast Descriptors)
%  101 : E-state keys (sums): S_sOH (Fast Descriptors)
%  102 : E-state keys (sums): S_dO (Fast Descriptors)
%  103 : E-state keys (sums): S_ssO (Fast Descriptors)
%  104 : Total energy (VAMP Electrostatics)
%  105 : Electronic energy (VAMP Electrostatics)
%  106 : Heat of formation (VAMP Electrostatics)
%  107 : HOMO eigenvalue (VAMP Electrostatics)
%  108 : LUMO eigenvalue (VAMP Electrostatics)
%  109 : Molecular surface area (VAMP Electrostatics)
%  110 : Molecular point group (VAMP Electrostatics)
%  111 : Total dipole (VAMP Electrostatics)
%  112 : Dipole x (VAMP Electrostatics)
%  113 : Dipole y (VAMP Electrostatics)
%  114 : Dipole z (VAMP Electrostatics)
%  115 : Quadrupole xx (VAMP Electrostatics)
%  116 : Quadrupole xy (VAMP Electrostatics)
%  117 : Quadrupole yy (VAMP Electrostatics)
%  118 : Quadrupole xz (VAMP Electrostatics)
%  119 : Quadrupole yz (VAMP Electrostatics)
%  120 : Quadrupole zz (VAMP Electrostatics)
%  121 : Octupole xxx (VAMP Electrostatics)
%  122 : Octupole xxy (VAMP Electrostatics)
%  123 : Octupole xxz (VAMP Electrostatics)
%  124 : Octupole xyy (VAMP Electrostatics)
%  125 : Octupole xyz (VAMP Electrostatics)
%  126 : Octupole xzz (VAMP Electrostatics)
%  127 : Octupole yyy (VAMP Electrostatics)
%  128 : Octupole yyz (VAMP Electrostatics)
%  129 : Octupole yzz (VAMP Electrostatics)
%  130 : Octupole zzz (VAMP Electrostatics)
%  131 : Mean polarizability (VAMP Electrostatics)