function subdbcorrcoeff = nmrsubdbcorrcoeff(dbcorrcoeff,substancetest,substanceref)
% NMRSUBDBCORRCOEFF extracts dbcorrcoeff data (output of NMRLOADCORRCOEFF) according to chosen test substances (in row) and reference substances (in column)
% SYNTAXES
%       subdbcorrcoeff = nmrsubdbcorr(dbcorrcoeff,{'mol1' 'mol2'},{'mol3' 'mol4'})
% INPUTS
%    dbcorrcoeff: matrix of corr coeff generated by NMRLOADCORRCOEFF
%  substancetest: list of test substances to be extracted (pattern), in row 
%                 - 1 x m cell {'mol1' 'mol2'}, extract data of substances having names 'mol1' and 'mol2'. Dupplicate names are not allowed
%                 - 1: m array [1 5], extract data of substances having indices 1 and 5; Duplicate indices are possible
%   substanceref: list of ref substances to be extracted, in column
%                 - ' ' : empty, extract the same substances as ref substances (default)
%                 - 1 x n cell {'mola' 'molb'}, extract data of substances having names 'mola' and 'molb'
%                 - 1 x n [1 5], extract data of substances (or mixtures) having indices 1 and 5
% 
% See also: nmrloadcorrcoeff
%
% RMNSPEC v 0.1 - 02/09/2013 - INRA\Olivier Vitrac, LNE\Mai Nguyen - rev.
%
% argcheck
if nargin < 2, error('2 arguments are required'), end
if nargin < 3, substanceref = {}; end
if ~isstruct(dbcorrcoeff) || ~isfield(dbcorrcoeff,'corrmean') || ~isfield(dbcorrcoeff,'corrmeanweight') || ~isfield(dbcorrcoeff,'subtestlist') || ~isfield(dbcorrcoeff,'subreflist') 
    error('DBCORRCOEFF must be created by NMRLOADCORRCOEFF')
end

fulllistofsubstancetest = dbcorrcoeff.subtestlist; % as dbcorr structure is N substancetest x M subtanceref
fulllistofsubstanceref = dbcorrcoeff.subreflist; % as dbcorr structure is N substancetest x M subtanceref

% check list of test subtances, pattern (in row)
%   -> check if inputs are numeric or cell of string
%   -> set indices of substances
if iscellstr(substancetest)     % list of subs test is string
    nsubstancetest = length(substancetest);
    if nsubstancetest > length(unique(substancetest)), error('substance keys must be unique, please check'), end
    [~,indsubtest] = intersect(fulllistofsubstancetest,substancetest);
    if length(indsubtest) < nsubstancetest
        dispf('ERROR\t%d values given as substance keys cannot be found',nsubstancetest-length(indsubtest))
        cellfun(@(m) dispf('\t''%s'' is missing',m),setdiff(substancetest,fulllistofsubstancetest))
        error('%d missing values (see above)',nsubstancetest-length(indsubtest))
    end
elseif isnumeric(substancetest)  % list of subs test is numeric (indices)
    if max(substancetest) > length(dbcorrcoeff.subtestlist), error('index of test substances is out of range'), end
    indsubtest = substancetest;
end
% if ~iscellstr(substancetest), error('the substance keys must be given in a cell array of strings (numerical values are excluded)'), end 

% check list of ref subtances (in column)
%   -> check if inputs are numeric or cell of string
%   -> set indices of substances
if ~isempty(substanceref)
    if iscellstr(substanceref)    % list of subs ref is string
        nsubstanceref = length(substanceref);
        if nsubstanceref > length(unique(substanceref)), error('substance keys must be unique, please check'), end
        [~,indsubref] = intersect(fulllistofsubstanceref,substanceref);
        if length(indsubref) < nsubstanceref
            dispf('ERROR\t%d values given as substance keys cannot be found',nsubstanceref-length(indsubref))
            cellfun(@(m) dispf('\t''%s'' is missing',m),setdiff(substanceref,fulllistofsubstanceref))
            error('%d missing values (see above)',nsubstanceref-length(indsubref))
        end
    elseif isnumeric(substanceref)
        if max(substanceref) > length(dbcorrcoeff.subreflist), error('index of ref substances is out of range'), end
        indsubref = substanceref;
    end
else   % no list of subs ref
    indsubref = indsubtest;  
end

% main (extract data)
subdbcorrcoeff = struct('corrmean',[],'corrmeanweight',[],'subtestlist',[],'subreflist',[]);
subdbcorrcoeff.corrmean = dbcorrcoeff.corrmean(indsubtest,indsubref);
subdbcorrcoeff.corrmeanweight = dbcorrcoeff.corrmeanweight(indsubtest,indsubref);
subdbcorrcoeff.subtestlist = dbcorrcoeff.subtestlist(indsubtest);
subdbcorrcoeff.subreflist = dbcorrcoeff.subreflist(indsubref);

