function plotnmrmatrix(dbcorrsub,dbcorrmix,varargin)
% PLOTNMRMATRIX plots matrix of correlation function in different modes with dbcorr (database of correlation calculated by NMRLOADMATRIX)
% SYNTAXES
%       figure, plotnmrmatrix(dbcorrsub,[],'level','substance','type','scalar')
% INPUTS
%           DBCORRMIX: matrix of correlation (corr. function) between substances generated by NMRLOADMATRIX
%           DBCORRMIX: matrix of correlation (corr. function) between substances and mixture(s) generated by NMRLOADMATRIX
%  VARARGIN
%                     'level': level of development of corr. matrix (elementary: by block or assemble)
%                            - 'block' : detailed format, plot separatly each motif of substance (vertically matrix)
%                            - 'substance' : put all motifs of substance together (squared matrix) (default)
%                      'type': type of data figured in plot (curve of corr. functions or color scale)
%                            - 'function' : detailed format, plot corr. functions (default)
%                            - 'scalar' : display only color corresponding to maxima of correlation value (or mean ofmaxi of correlation)
%                    'cscale': color scale
%                            - log, log scale (default)
%                            - linear, linear scale
%                    'parent': handle to plot
%             'paperposition': position of figure, (default = [])
%                 'papertype': type of paper (A3,A4...), (default = 'A4')
%                    'colref': color scale for background axis (default = [])
%              'colcurvediag': color of curve in diagonal (when i = j) (default=[])
%                  'colcurve': color of curve (default=[])
%                'colzerolag': color of point (cursor) at rezolag (default=[])
%                'whitevalue': thershold to transform text in white color (default = 0.7)
%                 'fontsize1': fontsize for text at level 1 (corresponding to substance names, at xlabel and ylabel), (default = 10)
%                 'fontsize2': fontsize for text at level 2 (corresponding position ppm, at ylabel), (default = 8)
%                'markersize': size of marker at zerolag
%            'rotationxlabel': rotation for text at xlabel (default = 0)
%            'rotationylabel': rotation for text at ylabel (default = 90)
% 'horizontalalignmentxlabel': horizontal alignement for text at xlabel ('center','left','right'...) (default = 'center')
% 'horizontalalignmentylabel': horizontal alignement for text at ylabel ('center','left','right'...) (default = 'center')
%    'verticalalignmentlabel': vertical alignement for text at x and y label ('middle','bottom'...) (default = 'bottom')
%          'colorbarposition': position of colorbar (default=[0.1570    0.1418    0.0063    0.2975])
%                'xposylabel': position at x axis for text for y label (default=.5)
%                'yposylabel': position at y axis for text for y label (default=.5)
%                'xposxlabel': position at x axis for text for x label (default=.5)
%                'yposxlabel': position at y axis for text for x label (default=.5)
%             'axislinewidth': linewidth of formatax of table (default=0.75)
%            'curvelinewidth': linewidth for curves (extradiagonal) (default=0.2)
%        'curvediaglinewidth': linewidth for diagonal curves (default=0.5)
%                   'rescale': threshold for rescaling of correlation values
%                'fontweight': font weight for x and y labels (default='normal')
%             'xlabelmixture': name of mixture used at xlabel (default='')
%                         'p': percentile parameter in generalizedBowleySkewness (default=0.1)
%                   'ythresh': paramter of threshold of y in generalizedBowleySkewness (default=0.05)
%                 'rowheight': vector of relative row heights, the last value is repeated as many times as necessary (default = 1)
%            'rotationzlabel': rotation or not for text of symmetry criterion (default = 0)
%
% KEYWORD
%      'colorbar' : display colorbar  
%       'weighted': take into account weight attributed by expert in dbmask for weighted mean of corr max and color of brackground of block
% 4 cases can be plotted: CAS 1 : block + function; CAS 2 : substance + function ; CAS 3 : block + scalar ; CAS 4 : substance + scalar
%
% EXAMPLES
% EX 1
% dbfit = nmrloaddbfit('path',fullfile(find_path_toolbox('rmnspec'),'data_pur'),'dbname','dbfit.mat');
% [~,dbxpur] = nmrloadbase;
% mol = {'BisphenolA' 'Triethylcitrate' 'Tinuvin326' 'CMIT'};
% weight = [1 1 1 1];
% [mixsp,ysubstance] = nmrbuildtheospec(mol,dbfit,dbxpur,weight); % theoretical mixture
% dbcorrsub = nmrloadmatrix(mol,[],dbxpur,dbfit,'verbose',2); % matrix of correlation between substances
% dbcorrmix = nmrloadmatrix(mol,mixsp(:,2),dbxpur,dbfit,'verbose',2);
% subdbcorrsub = nmrsubdbcorr(dbcorrsub,[1 3],[1 2 3 4]); subdbcorrmix = nmrsubdbcorr(dbcorrmix,1,[1 2 3 4]);
% plotnmrmatrix(dbcorrsub,dbcorrmix,'level','block')
% plotnmrmatrix(dbcorrsub,[],'level','block')
% plotnmrmatrix(dbcorrsub,dbcorrmix,'level','substance','paperposition',[0.3387   -0.0160   29.0000   21.0000],'paperorientation','landscape')
% plotnmrmatrix(dbcorrsub,dbcorrmix,'level','block','type','scalar')
% plotnmrmatrix(subdbcorrsub,subdbcorrmix,'level','block','type','function')
% plotnmrmatrix(subdbcorrsub,subdbcorrmix,'level','block','type','scalar')
% EX 2
% load(fullfile(find_path_toolbox('rmnspec'),'data_pur','deconvolution_example_corrsub.mat'));
% figname = 'correlation_full_subs_scalar';
% plotnmrmatrix(dbcorrsubfull,[],'level','substance','type','scalar','figname',figname,'paperposition',[0.3387   -0.0160   29.0000   21.0000],'fontsize1',6,'paperorientation','landscape',...
%               'rotationxlabel',90,'rotationylabel',0,'horizontalalignmentxlabel','left','horizontalalignmentylabel','right','verticalalignmentlabel','middle','colorbar') %,'cscale','linear')
% print_pdf(300,figname,figurefolder,'nocheck','PaperPositionMode','auto')
% print_png(300,figname,figurefolder,'',0,0,0)
% figname = 'correlation_full_block_scalar'; 
% plotnmrmatrix(dbcorrsubfull,[],'level','block','type','scalar','figname',figname,'paperposition',[0.3387   -0.0160   29.0000   21.0000],'fontsize1',5,'fontsize2',4,'paperorientation','landscape',...
%               'rotationxlabel',90,'rotationylabel',0,'horizontalalignmentxlabel','left','horizontalalignmentylabel','right','verticalalignmentlabel','middle','colorbar') %,'cscale','linear')
% print_pdf(300,figname,figurefolder,'nocheck','PaperPositionMode','auto')
% print_png(300,figname,figurefolder,'',0,0,0)

% See also: nmrloadmatrix, nmrsubdbcorr
%
% RMNSPEC v 0.1 - 28/08/2013 - INRA\Olivier Vitrac, LNE\Mai Nguyen - rev.
% 01/02/14
% History revision
% 18/09/13: add
% 'paperposition','paperorientation','papertype','colref','whitevalue','fontsize1','fontsize2','markersize'
%               'rotationxlabel','rotationylabel','horizontalalignmentxlabel','horizontalalignmentylabel','verticalalignmentlabel' as options 
%           and 'colorbar' as keywords
% 01/10/13: change CAS 2(substance + function) : display graphs, weighted mean or not for corrmax for brackground color
%           add color scale for important ppm position (according to weight attributed by expert)
%           add 'weighted' as keywords
% 02/10/13: add 'colcurvediag','colcurve','colzerolag' as options
% 03/10/13: add corrscale as scale value to rescaling of correlation value (for visibility of CAS 2)
% 08/10/13: add colorbarposition,xposylabel,yposylabel,xposxlabel,yposxlabel,axislinewidth,curvediaglinewidth',curvediaglinewidth,rescale,fontweight
% 21/11/13: add options to name mixture correlation (xlabel) 'xlabelmixture'
% 30/01/14: use surf and patch instead of imagesc for plot (cases 3 and 4)
% 31/01/14: add symetry criteria (using generalizedBowleySkewness)
% 01/02/14: compatibility issues with generalizedBowleySkewness
% 11/09/14: add 'rowheight' for determining height of each row
%               'rotationzlabel' for rotation of text of symmetry criterion

% default
default = struct('level','substance','type','function','parent',[],'figname','correlation','cscale','log','paperposition',[],'paperorientation','portrait','papertype','A4',...
                 'colref',[],'colcurvediag',[],'colcurve',[],'colzerolag',[],'whitevalue',0.7,'fontsize1',10,'fontsize2',8,'markersize',4,'rotationxlabel',0,'rotationylabel',0,...
                 'horizontalalignmentxlabel','center','horizontalalignmentylabel','center','verticalalignmentlabel','bottom','colorbarposition',[0.1570    0.1418    0.0063    0.2975],...
                 'xposylabel',.5,'yposylabel',.5,'xposxlabel',.5,'yposxlabel',.5,'axislinewidth',.75,'rescale',1e-5,'fontweight','normal','curvediaglinewidth',.5,'curvelinewidth',.2,...
                 'xlabelmixture','','p',0.1,'ythresh',0.05,'rowheight',1,'rotationzlabel',0);
keyword = {'colorbar','weighted'};

% argcheck
o = argcheck(varargin,default,keyword,'case');
o.rowheight = o.rowheight(:)';
if nargin < 1, error('1 argument is required'), end
if ~isstruct(dbcorrsub) || ~isfield(dbcorrsub,'corrmax') || ~isfield(dbcorrsub,'corrzerolag') || ~isfield(dbcorrsub,'rho2') || ~isfield(dbcorrsub,'subtestlist') || ~isfield(dbcorrsub,'subreflist') || ~isfield(dbcorrsub,'imax') || ~isfield(dbcorrsub,'centerpeak') || ~isfield(dbcorrsub,'corr') || ~isfield(dbcorrsub,'lags')    
    error('DBCORRSUB must be created by NMRLOADMATRIX with  at least verbose 2')
end
if ~isempty(dbcorrmix)
    if ~isstruct(dbcorrmix) || ~isfield(dbcorrmix,'corrmax') || ~isfield(dbcorrmix,'corrzerolag') || ~isfield(dbcorrmix,'rho2') || ~isfield(dbcorrmix,'subtestlist') || ~isfield(dbcorrmix,'subreflist') || ~isfield(dbcorrmix,'imax') || ~isfield(dbcorrmix,'centerpeak') || ~isfield(dbcorrmix,'corr') || ~isfield(dbcorrmix,'lags')    
        error('DBCORRMIX must be created by NMRLOADMATRIX with at least verbose 2')
    end
    if size(dbcorrsub,1) ~=  size(dbcorrmix,1), error('DBCORRSUB and DBCORRMIX must ahve a same size (fisrt direction, in row)'), end
    if size(dbcorrmix,2) > 1, warning('Only first mixture will be studied'), end
end

% develop of dbcorr for plot by blocks (separate motifs for each substance)
npattern = sum([dbcorrsub(:,1).npatternbysubtest]);
corrsub = cell(npattern,size(dbcorrsub,2)); % correlation of dbcorrsub grouped by substances
lagsub = cell(npattern,size(dbcorrsub,2)); % lags of dbcorrsub grouped by substances
for i = 1: size(dbcorrsub,2) % in column
    k = 1;
    for j = 1:size(dbcorrsub,1) % in row
        nROI = dbcorrsub(j,i).npatternbysubtest; 
        for l = 1:nROI
            corrsub{k,i} = dbcorrsub(j,i).corr{l,1};
            lagsub{k,i} = dbcorrsub(j,i).lags{l,1};
            k = k+1;
        end
    end
end
imaxsub = cell2mat(reshape({dbcorrsub.imax},size(dbcorrsub))); % index of max corr of dbcorrsub 
corrmaxsub = cell2mat(reshape({dbcorrsub.corrmax},size(dbcorrsub))); % max corr of dbcorrsub 
centerpeaksub = cell2mat(reshape({dbcorrsub.centerpeak},size(dbcorrsub))); % center of band of dbcorrsub 
weightsub = cell2mat(reshape({dbcorrsub.weight},size(dbcorrsub))); % weight of band of dbcorrsub 
gatesub = cell2mat(reshape({dbcorrsub.gate},size(dbcorrsub))); % gate of band of dbcorrsub

if ~isempty(dbcorrmix)
    corrmix = cell(npattern,size(dbcorrmix,2)); % correlation of dbcorrmix grouped by substances
    lagmix = cell(npattern,size(dbcorrmix,2)); % lags of dbcorrmix grouped by substances
    critsymetry = zeros(length(dbcorrmix),2); % symetry criterion: average value % modified OV 01/02/2014
    worstcritsymetry = zeros(length(dbcorrmix),2); % symetry criterion: worst case value % modified OV 01/02/2014
    for i = 1 % in column
        k = 1;
        for j = 1:size(dbcorrmix,1) % in row           
        nROI = dbcorrmix(j,i).npatternbysubtest;
        crittmp = zeros(nROI,2);
            for l = 1:nROI
                corrmix{k,i} = dbcorrmix(j,i).corr{l};
                lagmix{k,i} = dbcorrmix(j,i).lags{l};            
                k = k+1;
                if sum(dbcorrmix(j,i).corr{l})~=0
                    % modified OV 01/02/2014
                    crittmp(l,:) = generalizedBowleySkewness(dbcorrmix(j,i).lags{l}+dbcorrmix(j,i).lengthtest(l)+1-dbcorrmix(j,i).imax(l),dbcorrmix(j,i).corr{l},o.ythresh,o.p); 
                else crittmp(l,:) = 0; % modified OV 01/02/2014
                end
            end
            % modified OV 01/02/2014
            critsymetry(j,:) = mean(crittmp,1);
            for isym=1:2
                [~,bestcrit] = max(abs(crittmp(:,isym)));
                worstcritsymetry(j,isym) = crittmp(bestcrit,isym);
            end
            % end modified OV 01/02/2014
        end
    end
    imaxmix = cell2mat(reshape({dbcorrmix.imax},size(dbcorrmix)));   % index of max corr of dbcorrmix
    corrmaxmix = cell2mat(reshape({dbcorrmix.corrmax},size(dbcorrmix))); % max corr of dbcorrmix
    weightmix = cell2mat(reshape({dbcorrmix.weight},size(dbcorrmix))); % weight of each band in dbcorrmix
end

% mean of corr.max
corrmaxsubmean = zeros(size(dbcorrsub,1),size(dbcorrsub,2)); % mean of max corr of dbcorrsub (for background color scale)
if o.weighted
    for i = 1:size(dbcorrsub,1), for j = 1:size(dbcorrsub,2), corrmaxsubmean(i,j) = sum(dbcorrsub(i,j).corrmax.*dbcorrsub(i,j).weight,1)/sum(dbcorrsub(i,j).weight,1); end, end
    if ~isempty(dbcorrmix)
        corrmaxmixmean = zeros(size(dbcorrmix,1),size(dbcorrmix,2)); % mean of max corr of dbcorrmix (for background color scale)
        for i = 1:size(dbcorrmix,1),corrmaxmixmean(i,1) = sum(dbcorrmix(i,1).corrmax.*dbcorrmix(i,1).weight,1)/sum(dbcorrmix(i,1).weight,1); end
    end
else    
    for i = 1:size(dbcorrsub,1), for j = 1:size(dbcorrsub,2), corrmaxsubmean(i,j) = mean(dbcorrsub(i,j).corrmax); end, end
    if ~isempty(dbcorrmix)
        corrmaxmixmean = zeros(size(dbcorrmix,1),size(dbcorrmix,2)); % mean of max corr of dbcorrmix (for background color scale)
        for i = 1:size(dbcorrmix,1),corrmaxmixmean(i,1) = mean(dbcorrmix(i,1).corrmax); end
    end
end

% general axes for plot
if isempty(o.parent) 
    if ~isempty(o.figname), figname = o.figname; else figname = 'deconvolution'; end
    hfig = figure; formatfig(hfig,'figname',figname,'paperposition',o.paperposition,'paperorientation',o.paperorientation,'papertype',o.papertype,'color',[1 1 1],'inverthardcopy','off')
end

% whitevalue = o.whitevalue;
% color def
if strcmpi(o.cscale,'log'), coltransform = @log10;
else coltransform = @(x) x; 
end
if ~isempty(o.colref), colref = o.colref; else colref = cbrewer('seq','Greys',npattern); end
if ~isempty(o.colcurvediag), colcurvediag = o.colcurvediag; else colcurvediag = rgb('Crimson'); end
if ~isempty(o.colcurve), colcurve = o.colcurve; else colcurve = rgb('Green'); end
if ~isempty(o.colzerolag), colzerolag = o.colzerolag; else colzerolag = rgb('MediumBlue'); end
% color scale for ppm position and weight
colweight = @(w) interp1(linspace(min(weightsub(:)),max(weightsub(:)),npattern),cbrewer('seq','Reds',npattern),w); 
    
% plots
% ----- CAS 1 : block + function (detailed format)--------------------------------------------------------------------
 if strcmpi(o.level,'block') && strcmpi(o.type,'function') 
    % col scale    
    if o.weighted
        if ~isempty(dbcorrmix)
            cmin = min(min([corrmaxsub.*weightsub corrmaxmix.*weightmix])); cmax = max(max([corrmaxsub.*weightsub corrmaxmix.*weightmix])); 
        else
            cmin = min(min(corrmaxsub.*weightsub)); cmax = max(max(corrmaxsub.*weightsub));            
        end
    else
        if ~isempty(dbcorrmix)
            cmin = min(min([corrmaxsub corrmaxmix])); cmax = max(max([corrmaxsub corrmaxmix]));  
        else
            cmin = min(corrmaxsub(:)); cmax = max(corrmaxsub(:)); 
        end
    end
    valref = linspace(coltransform(max(cmin,1)),coltransform(cmax),npattern);
    colaxis = @(c) interp1(valref,colref,coltransform(max(c,1))); % color of axis according to max of corr.
    % subtance matrix
    hstmp = subplots([0.15 .7 .11 0.04],[.06 .94],[0 0.04],0);
    hmatrixsub = hstmp(4);
    ncolsmaj = size(dbcorrsub,2); nrowsmaj = size(dbcorrsub,1);    
    subplot(hmatrixsub), hblock = subplots(ones(1,ncolsmaj),[dbcorrsub(:,1).npatternbysubtest],0,0.05,'strict');
    ihblock=0;
    for i = 1:ncolsmaj
            lrow = 0;
        for j = 1:nrowsmaj
            ihblock = ihblock+1; 
            nrowsmin = dbcorrsub(j,i).npatternbysubtest; ncolsmin = 1; 
            subplot(hblock(ihblock)), hblockmin = subplots(ones(1,ncolsmin),ones(1,nrowsmin),0,0,'strict');
            for k = 1:dbcorrsub(j,i).npatternbysubtest
                lrow = lrow + 1;
                subplot(hblockmin(k)), hold on
                if i==j; %strcmp(dbcorrsub().subreflist,dbcorrsub().subtestlist)
                    plot(lagsub{lrow,i},corrsub{lrow,i},'color',colcurvediag,'linewidth',o.curvediaglinewidth) 
                else
                     plot(lagsub{lrow,i},corrsub{lrow,i},'color',colcurve,'linewidth',o.curvelinewidth)
                end
                plot(lagsub{lrow,i}(imaxsub(lrow,i)),corrmaxsub(lrow,i),'marker','s','markersize',o.markersize,'linestyle','none','markerfacecolor',colzerolag,'markeredgecolor',colzerolag) 
                plot([0 0],[min(ylim) max(ylim)],'--k','linewidth',1)
                axis tight %axis([])
                if o.weighted, formatax(gca,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'color',max(colaxis(corrmaxsub(lrow,i)*weightsub(lrow,i)),0),'LineWidth' ,o.axislinewidth) 
                else formatax(gca,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'color',max(colaxis(corrmaxsub(lrow,i)),0),'LineWidth',o.axislinewidth)
                end
            end
        end
    end
    % legend
    subplot(hstmp(1)), text(1,.5,sprintf('Position\n(ppm)'),'fontsize',10,'verticalalignment','middle','horizontalalignment','right')
    formatax(gca,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'LineWidth',o.axislinewidth)    
    % xlabel
    subplot(hstmp(3)), hxlabel = subplots(1,[1 1],0,0);
    formatax(hxlabel,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'LineWidth',o.axislinewidth)
    subplot(hxlabel(1)), text(0,.5,sprintf(' Spectra of pure substances \\rightarrow'),'fontsize',12,'verticalalignment','middle','horizontalalignment','left')
    subplot(hxlabel(2)), hxlabelmin = subplots(ones(1,ncolsmaj),1,0,0);
    for i = 1:ncolsmaj
        subplot(hxlabelmin(i)), text(o.xposxlabel,o.yposxlabel,dbcorrsub(1,i).subreflist,'fontsize',o.fontsize1,'verticalalignment',o.verticalalignmentlabel,'horizontalalignment',o.horizontalalignmentxlabel,'rotation',o.rotationxlabel,'fontweight',o.fontweight)
%         if ncolsmaj > 9, text(.5,0,dbcorrsub(1,i).subreflist,'fontsize',6,'verticalalignment','middle','horizontalalignment','left','rotation',90)
%         else text(.5,.5,dbcorrsub(1,i).subreflist,'fontsize',10,'verticalalignment','middle','horizontalalignment','center')
%         end
    end
    formatax(hxlabelmin,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'LineWidth',o.axislinewidth)
    % ylabel
    subplot(hstmp(2)), hylabel = subplots([.38 .41 .21],1,0,0);
    formatax(hylabel,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'LineWidth',o.axislinewidth)
    subplot(hylabel(1)), text(.5,1,sprintf('\\leftarrow Model patterns '),'fontsize',12,'verticalalignment','middle','horizontalalignment','right','rotation',90)
    
    subplot(hylabel(2)), hylabelname = subplots(1,[dbcorrsub(:,1).npatternbysubtest],0,0.05,'strict');
    formatax(hylabelname,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    for i = 1:nrowsmaj
        subplot(hylabelname(i)), text(o.xposylabel,o.yposylabel,dbcorrsub(i,1).subtestlist,'fontsize',o.fontsize1,'verticalalignment',o.verticalalignmentlabel,'horizontalalignment',o.horizontalalignmentylabel,'rotation',o.rotationylabel,'fontweight',o.fontweight)
%         if nrowsmaj > 9, text(1,.5,dbcorrsub(i,1).subtestlist,'fontsize',6,'verticalalignment','middle','horizontalalignment','right')
%         else text(.5,.5,dbcorrsub(i,1).subtestlist,'fontsize',10,'verticalalignment','middle','horizontalalignment','center','rotation',90)
%         end
    end
    
    subplot(hylabel(3)), hylabelpos = subplots(1,[dbcorrsub(:,1).npatternbysubtest],0,0.05,'strict');
    formatax(hylabelpos,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'LineWidth',o.axislinewidth)
    lrow = 0;
    for i = 1:nrowsmaj
        subplot(hylabelpos(i)), hylabelmin = subplots(1,ones(1,dbcorrsub(i,1).npatternbysubtest),0,0,'strict'); 
        formatax(hylabelmin,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
        for j = 1:dbcorrsub(i,1).npatternbysubtest
            lrow = lrow + 1;
            subplot(hylabelmin(j)), 
            if nrowsmaj > 7, text(.5,.5,sprintf('%0.3g',centerpeaksub(lrow,1)),'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','center')
            else text(.5,.5,sprintf('%0.3g\n%0.3g',gatesub(lrow,1:2)),'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','center')
            end
            formatax(gca,'color',colweight(dbcorrsub(i,1).weight(j)),'linewidth',o.axislinewidth)
        end
    end
    % colorbar
    if o.colorbar       
        colorbarcustom('orientation','vert','colormap',max(colaxis(linspace(max(cmin,1),cmax,20)),0),'position',o.colorbarposition,...
                       'ctick',ceil(linspace(cmin,cmax,5)),'ylim',[ceil(cmin) ceil(cmax)],'ytick',ceil(linspace(cmin,cmax,5)),'fontsize',6,'LineWidth',.5)   
        xlabel('max.corr.','fontsize',6)
    end
    % mixture matrix
    if ~isempty(dbcorrmix)
        subplot(hstmp(5))
        if isempty(o.xlabelmixture), text(.5,0,dbcorrmix(1).subreflist,'fontsize',o.fontsize1,'verticalalignment','bottom','horizontalalignment','center','fontweight',o.fontweight)
        else text(.5,0,o.xlabelmixture,'fontsize',o.fontsize1,'verticalalignment','bottom','horizontalalignment','center','fontweight',o.fontweight)
        end
        formatax(gca,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'LineWidth',o.axislinewidth)       
        hmatrixmix = hstmp(6);
        subplot(hmatrixmix), hblock = subplots(1,[dbcorrmix(:,1).npatternbysubtest],0,0.05,'strict'); 
        ihblock=0;
        for i = 1
                lrow = 0;
            for j = 1:size(dbcorrmix,1)
                ihblock = ihblock+1; 
                nrowsmin = dbcorrmix(j,i).npatternbysubtest; ncolsmin = 1; 
                subplot(hblock(ihblock)), hblockmin = subplots(ones(1,ncolsmin),ones(1,nrowsmin),0,0,'strict');
                for k = 1:dbcorrmix(j,1).npatternbysubtest
                    lrow = lrow + 1;
                    subplot(hblockmin(k)), hold on
                    plot(lagmix{lrow,i},corrmix{lrow,i},'color',colcurve,'linewidth',o.curvediaglinewidth)
                    plot(lagmix{lrow,i}(imaxmix(lrow,i)),corrmaxmix(lrow,i),'marker','s','markersize',o.markersize,'linestyle','none','markerfacecolor',colzerolag,'markeredgecolor',colzerolag) 
                    plot([0 0],[min(ylim) max(ylim)],'--k','linewidth',1)
                    axis tight %, axis([xlim ylim])
                    if o.weighted, formatax(gca,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'color',max(colaxis(corrmaxmix(lrow,i)*weightmix(lrow,i)),0),'LineWidth',o.axislinewidth)    
                    else formatax(gca,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'color',max(colaxis(corrmaxmix(lrow,i)),0),'LineWidth',o.axislinewidth)  
                    end
                end
            end
        end
        % modified 11/09/14
        for i = 1:size(dbcorrmix,1)
            subplot(hblock(i))
            % modified OV 01/02/2014
            if o.rotationzlabel == 0
                text(.5,.5,sprintf('\\bfds=%s\n(%s)\n\\rms=%s\n(%s)',... first line: mean (worst mean) / skewness (worst skewness)
                    formatsci(critsymetry(i,1),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,1),'economy','pattern','%0.2g'),...
                    formatsci(critsymetry(i,2),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,2),'economy','pattern','%0.2g') ...
                                  ),'fontsize',o.fontsize1,'verticalalignment','middle','horizontalalignment','center','rotation',o.rotationzlabel)
            % end modified OV 01/02/2014
%             subplot(hblock(i)), text(.5,.5,sprintf('%s\n(%s)',formatsci(critsymetry(i),'economy','pattern','%0.2g'),formatsci(worstcritsymetry(i),'economy','pattern','%0.2g')),'fontsize',o.fontsize1,'verticalalignment','middle','horizontalalignment','center')                
            else
                text(.5,.5,sprintf('\\bfds=%s (%s)\n\\rms=%s (%s)',... first line: mean (worst mean) / skewness (worst skewness)
                    formatsci(critsymetry(i,1),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,1),'economy','pattern','%0.2g'),...
                    formatsci(critsymetry(i,2),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,2),'economy','pattern','%0.2g') ...
                                  ),'fontsize',o.fontsize1,'verticalalignment','middle','horizontalalignment','center','rotation',o.rotationzlabel)
            end
        end
        formatax(hblock,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    else set(hstmp(5:8),'visible','off')
    end
 end    

% -----CAS 2 : substance + function ---------------------------------------------------------
if strcmpi(o.level,'substance') && strcmpi(o.type,'function') 
    % col scale
    if ~isempty(dbcorrmix)
        cmin = min(min([corrmaxsubmean corrmaxmixmean])); cmax = max(max([corrmaxsubmean corrmaxmixmean]));     
    else
        cmin = min(corrmaxsubmean(:));  cmax = max(corrmaxsubmean(:));        
    end
    valref = linspace(coltransform(max(cmin,1)),coltransform(cmax),npattern);
    colaxis = @(c) interp1(valref,colref,coltransform(max(c,1))); % color of axis according to max of corr.  
        
    % subtance matrix
    hstmp = subplots([.15 .69 .1 .06],[.06 .94],[0 0.03],0);
    hmatrixsub = hstmp(4);
    ncolsmaj = size(dbcorrsub,2); nrowsmaj = size(dbcorrsub,1);
    heights = [o.rowheight o.rowheight(end)*ones(1,nrowsmaj-length(o.rowheight))];
    subplot(hmatrixsub), hblock = subplots(ones(1,ncolsmaj),heights,0,0,'strict');    
    ihblock=0;
    for i = 1:ncolsmaj        % column-wise
        for j = 1:nrowsmaj    % row-wise
            ihblock = ihblock+1;
            subplot(hblock(ihblock)), hold on
            nROI = dbcorrsub(j,i).npatternbysubtest;
            [~,isort] = sort(dbcorrsub(j,i).corrzerolag); % sort according to corr. at zerolag for plotting
            shift = (max(vertcat(dbcorrsub(j,i).corr{:}))-min(vertcat(dbcorrsub(j,i).corr{:})))/nROI; %(max(dbcorrsub(j,i).corrmax)-min(dbcorrsub(j,i).corrmax))/nROI;
            corrscale = ceil(shift); % scale of correlation values for plot
            maxlength  = max(dbcorrsub(j,i).lengthtest); % maxima of lenght of spectrum segment
            tmpmaxcorr = 0; tmpmincorr = 0;  
            txtcurve = cellfun(@(i) sprintf('%s',char(96+i)),num2cell(1:length((dbcorrsub(j,i).centerpeak)')),'UniformOutput',false);
            for iROI = 1:nROI  
                if max(dbcorrsub(j,i).corr{isort(iROI),1}) > o.rescale
                    tmpcorr = dbcorrsub(j,i).corr{isort(iROI),1}/max(dbcorrsub(j,i).corr{isort(iROI),1})*corrscale+(iROI-1)*shift;
                else tmpcorr = dbcorrsub(j,i).corr{isort(iROI),1}+(iROI-1)*shift;
                end
                if i~=j, plot(dbcorrsub(j,i).lags{isort(iROI),1},tmpcorr,'color',colcurve,'linewidth',o.curvelinewidth) %max(dbcorrsub(j,i).corrmax)/3             
                else plot(dbcorrsub(j,i).lags{isort(iROI),1},tmpcorr,'color',colcurvediag,'linewidth',o.curvediaglinewidth) %max(dbcorrsub(j,i).corrmax)/3 
                end
                plot(dbcorrsub(j,i).lags{isort(iROI),1}(dbcorrsub(j,i).imax(isort(iROI),1)),tmpcorr(dbcorrsub(j,i).imax(isort(iROI),1)),...dbcorrsub(j,i).corrmax(isort(iROI),1)/max(dbcorrsub(j,i).corr{isort(iROI),1})*corrscale+(iROI-1)*shift
                     'marker','s','markersize',o.markersize,'linestyle','none','markerfacecolor',colzerolag,'markeredgecolor',colzerolag) 
                plot([0 0],[min(ylim) max(ylim)],'--k','linewidth',1) 
                if sum(colaxis(corrmaxsubmean(j,i)))<o.whitevalue
                    if mod(iROI,2), text(maxlength-5,mean(tmpcorr), {'\color[rgb]{.99 .99 .99}' txtcurve{isort(iROI)}},'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','right') %dbcorrsub(j,i).lags{isort(iROI),1}(end),max(dbcorrsub(j,i).corrmax)/3                      
                    else text(-maxlength+5,mean(tmpcorr), {'\color[rgb]{.99 .99 .99}' txtcurve{isort(iROI)}},'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','left') %dbcorrsub(j,i).lags{isort(iROI),1}(end),max(dbcorrsub(j,i).corrmax)/3                      
                    end
                else
                    if mod(iROI,2), text(maxlength-5,mean(tmpcorr),txtcurve{iROI},'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','right')
                    else text(-maxlength+5,mean(tmpcorr),txtcurve{iROI},'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','left')
                    end
                end
                tmpmaxcorr = max(tmpmaxcorr,max(tmpcorr)); tmpmincorr = min(tmpmincorr,min(tmpcorr));
            end
            axis([-maxlength-1 maxlength+1 tmpmincorr-corrscale/2 tmpmaxcorr+corrscale/2])   %xax = axis; axis tight %, 
            formatax(gca,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'color',max(colaxis(corrmaxsubmean(j,i)),0),'linewidth',o.axislinewidth)  
        end        
    end
    % legend
    % xlabel
    subplot(hstmp(3)), hxlabel = subplots(1,[1 1],0,0);
    formatax(hxlabel,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    subplot(hxlabel(1)), text(0,.5,sprintf(' Spectra of pure substances \\rightarrow'),'fontsize',12,'verticalalignment','middle','horizontalalignment','left')
    subplot(hxlabel(2)), hxlabelmin = subplots(ones(1,ncolsmaj),1,0,0);
    for i = 1:ncolsmaj
        subplot(hxlabelmin(i)),text(o.xposxlabel,o.yposxlabel,dbcorrsub(1,i).subreflist,'fontsize',o.fontsize1,'verticalalignment',o.verticalalignmentlabel,'horizontalalignment',o.horizontalalignmentxlabel,'rotation',o.rotationxlabel,'fontweight',o.fontweight)
    end
    formatax(hxlabelmin,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    % ylabel
    subplot(hstmp(2)), hylabel = subplots([.4 .6],1,0,0);
    formatax(hylabel,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    subplot(hylabel(1)), text(.5,1,sprintf('\\leftarrow Model patterns '),'fontsize',12,'verticalalignment','middle','horizontalalignment','right','rotation',90)
    
    subplot(hylabel(2)), hylabelname = subplots(1,heights,0,0,'strict');
    formatax(hylabelname,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    for i = 1:nrowsmaj
        tmpppm = (dbcorrsub(i).centerpeak)';
        txtylabel = cellfun(@(m,p) sprintf('\\fontsize{%0.2g}%s: %0.3gppm',o.fontsize2,char(96+m),p),num2cell(1:length(tmpppm)),num2cell(tmpppm,1),'UniformOutput',false); 
        subplot(hylabelname(i)), text(o.xposylabel,o.yposylabel,vertcat(dbcorrsub(i,1).subtestlist,txtylabel'),'fontsize',o.fontsize1,'verticalalignment',o.verticalalignmentlabel,'horizontalalignment',o.horizontalalignmentylabel,'rotation',o.rotationylabel,'fontweight',o.fontweight) %dbcorrsub(i,1).subtestlist
    end
    % colorbar
    if o.colorbar
        colorbarcustom('orientation','vert','colormap',max(colaxis(linspace(max(cmin,1),cmax,20)),0),...
                       'position',o.colorbarposition,'ctick',ceil(linspace(cmin,cmax,5)),'ylim',[ceil(cmin) ceil(cmax)],...[0.1583    0.1418    0.0040    0.1044]
                       'ytick',ceil(linspace(cmin,cmax,5)),'fontsize',6,'LineWidth',.5)
        xlabel('max.corr.','fontsize',6)
    end
    
    % mixture matrix
    if ~isempty(dbcorrmix)
        subplot(hstmp(5))
        if isempty(o.xlabelmixture), text(.5,0,dbcorrmix(1).subreflist,'fontsize',o.fontsize1,'verticalalignment','bottom','horizontalalignment','center','fontweight',o.fontweight)
        else text(.5,0,o.xlabelmixture,'fontsize',o.fontsize1,'verticalalignment','bottom','horizontalalignment','center','fontweight',o.fontweight)
        end
        formatax(gca,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)       
        hmatrixmix = hstmp(6);
        subplot(hmatrixmix), hblock = subplots(1,heights,0,0,'strict'); 
        ihblock=0;
        for i = 1
            for j = 1:size(dbcorrmix,1)
                ihblock=ihblock+1;
                subplot(hblock(ihblock)), hold on
                nROI = dbcorrmix(j,i).npatternbysubtest;
                [~,isort] = sort(dbcorrmix(j,i).corrzerolag); % sort according to corr. at zerolag for plotting
                shift = (max(vertcat(dbcorrmix(j,i).corr{:}))-min(vertcat(dbcorrmix(j,i).corr{:})))/nROI; %shift = (max(dbcorrmix(j,i).corrmax)-min(dbcorrmix(j,i).corrmax))/nROI;
                corrscale = ceil(shift); % scale of correlation values for plot
                maxlength  = max(dbcorrmix(j,i).lengthtest); % maxima of lenght of spectrum segment
                tmpmaxcorr = 0; tmpmincorr = 0;
                txtcurve = cellfun(@(i) sprintf('%s',char(96+i)),num2cell(1:length((dbcorrmix(j,i).centerpeak)')),'UniformOutput',false);
                for iROI = 1:nROI  
                    if max(dbcorrsub(j,i).corr{isort(iROI),1}) > o.rescale
                        tmpcorr = max(0,dbcorrmix(j,i).corr{isort(iROI),1}/max(dbcorrmix(j,i).corr{isort(iROI),1})*corrscale+(iROI-1)*shift);
                    else tmpcorr = dbcorrmix(j,i).corr{isort(iROI),1}+(iROI-1)*shift;
                    end                    
                    plot(dbcorrmix(j,i).lags{isort(iROI),1}(dbcorrmix(j,i).imax(isort(iROI),1)),tmpcorr(dbcorrmix(j,i).imax(isort(iROI),1)),...dbcorrmix(j,i).corrmax(isort(iROI),1)/max(dbcorrmix(j,i).corr{isort(iROI),1})*corrscale+(iROI-1)*shift
                        'marker','s','markersize',o.markersize,'linestyle','none','markerfacecolor',colzerolag,'markeredgecolor',colzerolag) 
                    plot(dbcorrmix(j,i).lags{isort(iROI),1},tmpcorr,'color',colcurve,'linewidth',o.curvediaglinewidth)
                    plot([0 0],[min(ylim) max(ylim)],'--k','linewidth',1)
                    if sum(colaxis(corrmaxmixmean(j,i)))<o.whitevalue
                        if mod(iROI,2), text(maxlength-5,mean(tmpcorr),{'\color[rgb]{.99 .99 .99}' txtcurve{isort(iROI)}},'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','right')
                        else text(-maxlength+5,mean(tmpcorr),{'\color[rgb]{.99 .99 .99}' txtcurve{isort(iROI)}},'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','left')
                        end
                    else
                        if mod(iROI,2), text(maxlength-5,mean(tmpcorr),txtcurve{isort(iROI)},'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','right')
                        else text(-maxlength+5,mean(tmpcorr),txtcurve{isort(iROI)},'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','left')
                        end
                    end
                    tmpmaxcorr = max(tmpmaxcorr,max(tmpcorr)); tmpmincorr = min(tmpmincorr,min(tmpcorr));
                end
                axis([-maxlength-1 maxlength+1 tmpmincorr-corrscale/2 tmpmaxcorr+corrscale/2])   %axis tight, axis([xlim ylim]) 
                formatax(gca,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'color',max(colaxis(corrmaxmixmean(j,i)),0),'linewidth',o.axislinewidth) 
            end
        end
        subplot(hstmp(8)), hblock = subplots(1,heights,0,0,'strict');
        % modified 11/09/14
        for i = 1:size(dbcorrmix,1)
            subplot(hblock(i))
            % modified OV 01/02/2014
            if o.rotationzlabel == 0
                text(.5,.5,sprintf('\\bfds=%s\n(%s)\n\\rms=%s\n(%s)',... first line: mean (worst mean) / skewness (worst skewness)
                    formatsci(critsymetry(i,1),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,1),'economy','pattern','%0.2g'),...
                    formatsci(critsymetry(i,2),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,2),'economy','pattern','%0.2g') ...
                                  ),'fontsize',o.fontsize1,'verticalalignment','middle','horizontalalignment','center','rotation',o.rotationzlabel)
            % end modified OV 01/02/2014
%             subplot(hblock(i)), text(.5,.5,sprintf('%s\n(%s)',formatsci(critsymetry(i),'economy','pattern','%0.2g'),formatsci(worstcritsymetry(i),'economy','pattern','%0.2g')),'fontsize',o.fontsize1,'verticalalignment','middle','horizontalalignment','center')                
            else
                text(.5,.5,sprintf('\\bfds=%s (%s)\n\\rms=%s (%s)',... first line: mean (worst mean) / skewness (worst skewness)
                    formatsci(critsymetry(i,1),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,1),'economy','pattern','%0.2g'),...
                    formatsci(critsymetry(i,2),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,2),'economy','pattern','%0.2g') ...
                                  ),'fontsize',o.fontsize1,'verticalalignment','middle','horizontalalignment','center','rotation',o.rotationzlabel)
            end
        end
        formatax(hblock,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth) 
    else set(hstmp(5:8),'visible','off')
    end
    set(hstmp([1 7]),'visible','off')
end

% -----CAS 3 : block + scalar ---------------------------------------------------------------
if strcmpi(o.level,'block') && strcmpi(o.type,'scalar')
    % col scale    
    if o.weighted
        if ~isempty(dbcorrmix)
            cmin = min(min([corrmaxsub.*weightsub corrmaxmix.*weightmix])); cmax = max(max([corrmaxsub.*weightsub corrmaxmix.*weightmix])); 
        else
            cmin = min(min(corrmaxsub.*weightsub)); cmax = max(max(corrmaxsub.*weightsub));            
        end
    else
        if ~isempty(dbcorrmix)
            cmin = min(min([corrmaxsub corrmaxmix])); cmax = max(max([corrmaxsub corrmaxmix]));  
        else
            cmin = min(corrmaxsub(:)); cmax = max(corrmaxsub(:)); 
        end
    end
    valref = linspace(coltransform(max(cmin,1)),coltransform(cmax),npattern);
    colaxis = @(c) interp1(valref,colref,coltransform(max(c,1))); % color of axis according to max of corr.     
    % subtance matrix
    hstmp = subplots([0.15 .7 .11 0.04],[.3 .7],[0 0.04],0);
    subplot(hstmp(4)), imagesc(corrmaxsub);
    colormap(max(colaxis(linspace(cmin,cmax,npattern)),0))  %colormap(max(colaxis(linspace(min(corrmaxsub(:)),max(corrmaxsub(:)),npattern)),0)) 
    formatax(gca,'xtick',[],'ytick',[],'xticklabel',' ','yticklabel',' ','linewidth',o.axislinewidth)
    ncolsmaj = size(dbcorrsub,2); nrowsmaj = size(dbcorrsub,1);
    % legend
    subplot(hstmp(1)), text(1,.5,sprintf('Position\n(ppm)'),'fontsize',10,'verticalalignment','middle','horizontalalignment','right')
    formatax(gca,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)    
    % xlabel
    subplot(hstmp(3)), hxlabel = subplots(1,[1 1],0,0);
    formatax(hxlabel,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    subplot(hxlabel(1)), text(0,.5,sprintf(' Spectra of pure substances \\rightarrow'),'fontsize',12,'verticalalignment','middle','horizontalalignment','left')
    subplot(hxlabel(2)), hxlabelmin = subplots(ones(1,ncolsmaj),1,0,0);
    for i = 1:ncolsmaj
        subplot(hxlabelmin(i)), text(o.xposxlabel,o.yposxlabel,dbcorrsub(1,i).subreflist,'fontsize',o.fontsize1,'verticalalignment',o.verticalalignmentlabel,'horizontalalignment',o.horizontalalignmentxlabel,'rotation',o.rotationxlabel,'fontweight',o.fontweight)
    end
    formatax(hxlabelmin,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    % ylabel
    subplot(hstmp(2)), hylabel = subplots([.38 .41 .21],1,0,0);
    formatax(hylabel,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    subplot(hylabel(1)), text(.5,1,sprintf('\\leftarrow Model patterns '),'fontsize',12,'verticalalignment','middle','horizontalalignment','right','rotation',90)
    
    subplot(hylabel(2)), hylabelname = subplots(1,[dbcorrsub(:,1).npatternbysubtest],0,0,'strict');
    formatax(hylabelname,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    for i = 1:nrowsmaj
        subplot(hylabelname(i)), text(o.xposylabel,o.yposylabel,dbcorrsub(i,1).subtestlist,'fontsize',o.fontsize1,'verticalalignment',o.verticalalignmentlabel,'horizontalalignment',o.horizontalalignmentylabel,'rotation',o.rotationylabel,'fontweight',o.fontweight)
    end
    
    subplot(hylabel(3)), hylabelpos = subplots(1,[dbcorrsub(:,1).npatternbysubtest],0,0,'strict');
    formatax(hylabelpos,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    lrow = 0;
    for i = 1:nrowsmaj
        nrowsmin = dbcorrsub(i,1).npatternbysubtest;
        subplot(hylabelpos(i)), hylabelmin = subplots(1,ones(1,nrowsmin),0,0,'strict'); 
        formatax(hylabelmin,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
        for j = 1:nrowsmin
            lrow = lrow + 1;
            subplot(hylabelmin(j)), text(.5,.5,sprintf('%0.3g',centerpeaksub(lrow,1)),'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','center')
        end
    end
    % colorbar
    if o.colorbar
        colorbarcustom('orientation','vert','colormap',max(colaxis(linspace(max(cmin,1),cmax,20)),0),...
                       'position',o.colorbarposition,'ctick',ceil(linspace(cmin,cmax,5)),'ylim',[ceil(cmin) ceil(cmax)],...
                       'ytick',ceil(linspace(cmin,cmax,5)),'fontsize',6,'LineWidth',.5)
        xlabel('max.corr.','fontsize',6)
    end
    
    % mixture matrix
    if ~isempty(dbcorrmix)
        subplot(hstmp(5))
        if isempty(o.xlabelmixture), text(.5,0,dbcorrmix(1).subreflist,'fontsize',o.fontsize1,'verticalalignment','bottom','horizontalalignment','center','fontweight',o.fontweight)
        else text(.5,0,o.xlabelmixture,'fontsize',o.fontsize1,'verticalalignment','bottom','horizontalalignment','center','fontweight',o.fontweight)
        end
        formatax(gca,'xtick',[],'ytick',[],'xticklabel',' ','yticklabel',' ','linewidth',o.axislinewidth)
        subplot(hstmp(6)), imagesc(corrmaxmix)
        colormap(max(colaxis(linspace(cmin,cmax,npattern)),0)) %colormap(max(colaxis(linspace(max(min(corrmaxmix(:)),1),max(corrmaxmix(:)),npattern)),0))
        formatax(gca,'xtick',[],'ytick',[],'xticklabel',' ','yticklabel',' ','linewidth',o.axislinewidth)
        % modified 11/09/14
        for i = 1:size(dbcorrmix,1)
            subplot(hblock(i))
            % modified OV 01/02/2014
            if o.rotationzlabel == 0
                text(.5,.5,sprintf('\\bfds=%s\n(%s)\n\\rms=%s\n(%s)',... first line: mean (worst mean) / skewness (worst skewness)
                    formatsci(critsymetry(i,1),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,1),'economy','pattern','%0.2g'),...
                    formatsci(critsymetry(i,2),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,2),'economy','pattern','%0.2g') ...
                                  ),'fontsize',o.fontsize1,'verticalalignment','middle','horizontalalignment','center','rotation',o.rotationzlabel)
            % end modified OV 01/02/2014
%             subplot(hblock(i)), text(.5,.5,sprintf('%s\n(%s)',formatsci(critsymetry(i),'economy','pattern','%0.2g'),formatsci(worstcritsymetry(i),'economy','pattern','%0.2g')),'fontsize',o.fontsize1,'verticalalignment','middle','horizontalalignment','center')                
            else
                text(.5,.5,sprintf('\\bfds=%s (%s)\n\\rms=%s (%s)',... first line: mean (worst mean) / skewness (worst skewness)
                    formatsci(critsymetry(i,1),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,1),'economy','pattern','%0.2g'),...
                    formatsci(critsymetry(i,2),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,2),'economy','pattern','%0.2g') ...
                                  ),'fontsize',o.fontsize1,'verticalalignment','middle','horizontalalignment','center','rotation',o.rotationzlabel)
            end
        end
        formatax(hblock,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    else set(hstmp(5:8),'visible','off')
    end
end

% -----CAS 4 : substance + scalar ------------------------------------------------------------
if strcmpi(o.level,'substance') && strcmpi(o.type,'scalar') 
    % color scale
    if ~isempty(dbcorrmix)
        cmin = min(min([corrmaxsubmean corrmaxmixmean])); cmax = max(max([corrmaxsubmean corrmaxmixmean]));   
    else
        cmin = min(corrmaxsubmean(:)); cmax = max(corrmaxsubmean(:));
    end
    valref = linspace(coltransform(max(cmin,1)),coltransform(cmax),npattern);
    colaxis = @(c) interp1(valref,colref,coltransform(max(c,1))); % color of axis according to max of corr.  
    % substance matrix 
    hstmp = subplots([0.25 .5 .15 0.1],[.25 .75],[0 0.04],0);
    ncolsmaj = size(dbcorrsub,2); nrowsmaj = size(dbcorrsub,1); 
    [X,Y] = meshgrid(0:ncolsmaj,0:nrowsmaj);
    p = surf2patch(X,Y,X*0);
    cdata =  max(colaxis(flipud(corrmaxsubmean)),0);
    subplot(hstmp(4)), hpatch = patch(p,'FaceColor','flat','CData',cdata);
%     subplot(hmatrixsub), imagesc(corrmaxsubmean)
%     colormap(max(colaxis(linspace(cmin,cmax,npattern)),0)) %colormap(max(colaxis(linspace(min(corrmaxsubmean(:)),max(corrmaxsubmean(:)),npattern)),0))
    xlim([0 ncolsmaj])    
    % modified 12/09/14
    formatax(hstmp(4),'xtick',[],'ytick',[],'xticklabel',' ','yticklabel',' ','linewidth',o.axislinewidth/10)
    set(hstmp(4),'visible','off'), drawnow
    objhstmp = obj2im(hpatch,'fig600',fullfile(tempdir,'plotnmrmatrix')); cla, htmp = plotobj(objhstmp);

    %%%%
    % legend
    % xlabel
    subplot(hstmp(3)), hxlabel = subplots(1,[0.3 0.7],0,0);
    formatax(hxlabel,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    subplot(hxlabel(1)), text(0,.5,sprintf(' Spectra of pure substances \\rightarrow'),'fontsize',12,'verticalalignment','middle','horizontalalignment','left')
    subplot(hxlabel(2)), hxlabelmin = subplots(ones(1,ncolsmaj),1,0,0);
    for i = 1:ncolsmaj
        subplot(hxlabelmin(i)), text(o.xposxlabel,o.yposxlabel,dbcorrsub(1,i).subreflist,'fontsize',o.fontsize1,'verticalalignment',o.verticalalignmentlabel,'horizontalalignment',o.horizontalalignmentxlabel,'rotation',o.rotationxlabel,'fontweight',o.fontweight)
    end
    formatax(hxlabelmin,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    % ylabel
    subplot(hstmp(2)), hylabel = subplots([.4 .6],1,0,0);
    formatax(hylabel,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    subplot(hylabel(1)), text(.5,1,sprintf('\\leftarrow Model patterns '),'fontsize',12,'verticalalignment','middle','horizontalalignment','right','rotation',90)
    
    subplot(hylabel(2)), hylabelname = subplots(1,ones(1,nrowsmaj),0,0,'strict');
    formatax(hylabelname,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    for i = 1:nrowsmaj
        subplot(hylabelname(i)),text(o.xposylabel,o.yposylabel,dbcorrsub(i,1).subtestlist,'fontsize',o.fontsize1,'verticalalignment',o.verticalalignmentlabel,'horizontalalignment',o.horizontalalignmentylabel,'rotation',o.rotationylabel,'fontweight',o.fontweight)
    end
    % color bar
    if o.colorbar
        colorbarcustom('orientation','vert','colormap',max(colaxis(linspace(max(cmin,1),cmax,20)),0),...
                       'position',o.colorbarposition,'ctick',ceil(linspace(cmin,cmax,5)),'ylim',[ceil(cmin) ceil(cmax)],...
                       'ytick',ceil(linspace(cmin,cmax,5)),'fontsize',6,'LineWidth',.5)
        xlabel('max.corr.','fontsize',6)
    end
    
    % mixture matrix
    if ~isempty(dbcorrmix)
        subplot(hstmp(5))
        if isempty(o.xlabelmixture), text(.5,0,dbcorrmix(1).subreflist,'fontsize',o.fontsize1,'verticalalignment','bottom','horizontalalignment','center','fontweight',o.fontweight)
        else text(.5,0,o.xlabelmixture,'fontsize',o.fontsize1,'verticalalignment','bottom','horizontalalignment','center','fontweight',o.fontweight)
        end
        formatax(gca,'xtick',[],'ytick',[],'xticklabel',' ','yticklabel',' ','linewidth',o.axislinewidth)
        [X,Y] = meshgrid(0:1,0:nrowsmaj);
        p = surf2patch(X,Y,X*0);
        cdata =  max(colaxis(flipud(corrmaxmixmean)),0);
        subplot(hstmp(6)), hpatch = patch(p,'FaceColor','flat','FaceVertexCData',cdata);    
%         subplot(hmatrixmix), imagesc(corrmaxmixmean)
%         colormap(max(colaxis(linspace(cmin,cmax,npattern)),0)) %colormap(max(colaxis(linspace(min(corrmaxmixmean(:)),max(corrmaxmixmean(:)),npattern)),0))
        formatax(gca,'xtick',[],'ytick',[],'xticklabel',' ','yticklabel',' ','linewidth',o.axislinewidth/10)
        % modified 12/09/14
        set(hstmp(6),'visible','off'), drawnow
        objhstmp = obj2im(hpatch,'fig600',fullfile(tempdir,'plotnmrmatrix')); cla, htmp = plotobj(objhstmp);
        %%%%%
        subplot(hstmp(8)), hblock = subplots(1,ones(1,nrowsmaj),0,0,'strict');
        % modified 11/09/14
        for i = 1:size(dbcorrmix,1)
            subplot(hblock(i))
            % modified OV 01/02/2014
            if o.rotationzlabel == 0
                text(.5,.5,sprintf('\\bfds=%s\n(%s)\n\\rms=%s\n(%s)',... first line: mean (worst mean) / skewness (worst skewness)
                    formatsci(critsymetry(i,1),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,1),'economy','pattern','%0.2g'),...
                    formatsci(critsymetry(i,2),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,2),'economy','pattern','%0.2g') ...
                                  ),'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','center','rotation',o.rotationzlabel)
            % end modified OV 01/02/2014
%             subplot(hblock(i)), text(.5,.5,sprintf('%s\n(%s)',formatsci(critsymetry(i),'economy','pattern','%0.2g'),formatsci(worstcritsymetry(i),'economy','pattern','%0.2g')),'fontsize',o.fontsize1,'verticalalignment','middle','horizontalalignment','center')                
            else
                text(.5,.5,sprintf('\\bfds=%s (%s)\n\\rms=%s (%s)',... first line: mean (worst mean) / skewness (worst skewness)
                    formatsci(critsymetry(i,1),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,1),'economy','pattern','%0.2g'),...
                    formatsci(critsymetry(i,2),'economy','pattern','%0.2g'), ...
                    formatsci(worstcritsymetry(i,2),'economy','pattern','%0.2g') ...
                                  ),'fontsize',o.fontsize2,'verticalalignment','middle','horizontalalignment','center','rotation',o.rotationzlabel)
            end
        end
        formatax(hblock,'yticklabel',' ','ytick',[],'xticklabel',' ','xtick',[],'linewidth',o.axislinewidth)
    else set(hstmp(5:8),'visible','off')
    end
    set(hstmp([1 7]),'visible','off')
end